# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 408bb8b77ab582de157111a8c7feabffa4c4a16b2c183da3de3c0b9ca5dd7f79144ef633b293d433505df59c8636f8e029013e86444d2cfbc03a45598c3f8483

test:
  secret_key_base: ac8ed5a8bdd4d8c141fe7cae605adac5daa60fc6ef5dce9f7449e3f883b9114d811f81f7bce17486a7e3c04b9643c8beed523c9494e3ba2471407b0cb54889a8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
